config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'wines#index'
  resources :wines, only: [:index, :show]
  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  monetize :amount_cents
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
  monetize :price_cents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
    @order = current_user.orders.where(state: 'paid').find(params[:id])
  end

  def create
    wine = Wine.find(params[:wine_id])
    order = Order.create!(wine_sku: wine.sku, amount: wine.price, state: 'pending', user: current_user)

    redirect_to new_order_payment_path(order)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Payment for wine #{@order.wine_sku} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    redirect_to order_path(@order)
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @wines = Wine.all
  end

  def show
    @wine = Wine.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shop - Chateau Angludet</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <h1>Toutes mes commandes</h1>
  <% @orders.each do |order| %>
    <div class="message">
      <div class="message-name">
        <h3><%= order.wine_sku %></h3>
        <p><%= order.created_at %></p>
      </div>
      <div class="message-body">
        <p><strong>Une bonne bouteille d'Angludet</strong></p>
        <p>
          La bouteille qui vous redonnera le sourir!
        </p>
      </div>
      <div class="message-status">
        <% if order.state == "pending" %>
          <p class="status pending">Pending</p>
        <% elsif order.state == "paid" %>
          <p class="status accepted">Paid</p>
        <% else %>
          <p class="status declined">Declined</p>
        <% end %>
        <p class="price"><%= humanized_money_with_symbol(order.amount_cents * 10) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h1>Commande</h1>
  <ul>
    <li>Status: <%= @order.state %></li>
    <li>Item: <%= @order.wine_sku %></li>
    <li>Amount: <%= humanized_money_with_symbol(@order.amount) %></li>
  <ul>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container text-center">
    <h1>Chateau Angludet</h1>
    <h4>E-shop</h4>
  </div>
</div>

app/views/payments/new.html.erb
<h1>Purchase of Wine <%= @order.wine_sku %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Wine"
    data-email="<%= current_user.email %>"
    data-description="Wine <%= @order.wine_sku %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>">
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar py-3 px-4">
  <a class="logo" href="/">
    <%= image_tag "logo-texte-angludet.png", height: 75 %>
  </a>
  <div class="nav-bar-right d-flex align-items-center">
    <%= link_to "Profile", "#", class: "px-3 d-none d-sm-block" %>
    <%= link_to "Commandes", orders_path, class: "px-3 d-none d-sm-block" %>
    <%= link_to "Login", new_user_session_path, class: "px-3 d-none d-sm-block" %>
    <div class="dropdown  d-none d-sm-block">
      <%= image_tag "http://www.placehold.it/40x40", class: "rounded-circle px-3", alt:"avatar", type: "image", id: "dropdownMenuButton", data: { toggle:"dropdown" }, aria: { haspopup:"true", expanded: "false" } %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Action", "#", class: "dropdown-item" %>
        <%= link_to "Another action", "#", class: "dropdown-item" %>
        <%= link_to "Sign_out", destroy_user_session_path, class: "dropdown-item" %>
      </div>
    </div>
  </div>
  <div class="dropdown burger d-block d-sm-none">
    <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
     <%= link_to "Action", "#", class: "dropdown-item" %>
     <%= link_to "Another action", "#", class: "dropdown-item" %>
     <%= link_to "Sign_out", destroy_user_session_path, class: "dropdown-item" %>
    </div>
  </div>
</div>

app/views/wines/index.html.erb
<div class="container">
  <h1 class="text-center">Les vins</h1>
  <div class="row">
    <% @wines.each do |wine| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <h3><%= link_to wine.name, wine_path(wine) %></h3>
          <%= link_to image_tag(wine.photo_url, width: '200px'), wine_path(wine) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/wines/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @wine.name %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <%= image_tag(@wine.photo_url, width: '100%') %>
    </div>
    <div class="col-sm-12 col-md-6">
      <p>Some awesome description of our amazing wine.</p>
      <p>Prix: <%= humanized_money_with_symbol(@wine.price) %></p>
    </div>
  </div>
  <%= form_tag orders_path do %>
    <%= hidden_field_tag 'wine_id', @wine.id %>
    <%= submit_tag 'Commander', class: 'btn btn-primary' %>
  <% end %>
</div>